import cv2

try:
    from . import config_local as _local
except ImportError:
    _local = None


def _local_or_default(name, default):
    if _local is None:
        return default
    return getattr(_local, name, default)


WINDOW_NAME = "Security AI"
ALERT_WINDOW_NAME = "Security Alert"
MAIN_WINDOW_X = 80
MAIN_WINDOW_Y = 80
MAIN_WINDOW_WIDTH = 960
MAIN_WINDOW_HEIGHT = 720
ALERT_WINDOW_GAP = 24

CAMERA_INDEX = _local_or_default("CAMERA_INDEX", 2)
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
CAMERA_BUFFER_SIZE = 1
PORTRAIT_ROTATION = None
ALERT_HOLD_SECONDS = 3.0
DELETE_OUTPUTS_ON_EXIT = True

CAMERA_BLOCK_CHANGE_RATIO_THRESHOLD = 0.35
CAMERA_BLOCK_MIN_BRIGHTNESS = 40.0
CAMERA_BLOCK_MIN_PIXEL_STD = 15.0
CAMERA_BLOCK_CAPTURE_INTERVAL_SECONDS = 1.0

WEAPON_MODEL_PATH = "models/yolo11n.pt"
POSE_MODEL_PATH = "models/yolo11n-pose.pt"
PERSON_MODEL_PATH = "models/yolo11n.pt"
PERSON_CONFIDENCE = 0.2
PERSON_IMAGE_SIZE = 960
LOITERING_THRESHOLD_SECONDS = 20.0

WEAPON_LABELS = _local_or_default("WEAPON_LABELS", {"knife", "baseball bat"})
PERSON_NEAR_AREA_THRESHOLD = 0.7
PERSON_NEAR_REQUIRED_TIME_SECONDS = 2.0
PERSON_NEAR_MIN_CONFIDENCE = 0.35
PERSON_NEAR_COOLDOWN_SECONDS = 3.0
DOOR_LOCK_ROI_X_RATIO = 0.30
DOOR_LOCK_ROI_Y_RATIO = 0.65
DOOR_LOCK_ROI_WIDTH_RATIO = 0.15
DOOR_LOCK_ROI_HEIGHT_RATIO = 0.23
DOOR_LOCK_WRIST_CONFIDENCE_THRESHOLD = 0.5
DOOR_LOCK_REQUIRED_SECONDS = 2.0
DOOR_LOCK_MOVEMENT_HISTORY_SIZE = 20
DOOR_LOCK_DECAY_FRAMES = 2
DOOR_LOCK_MOVEMENT_DELTA_THRESHOLD = 40
DOOR_LOCK_COOLDOWN_SECONDS = 3.0

POSE_CONNECTIONS = [
    (0, 1), (0, 2), (1, 3), (2, 4),
    (5, 6), (5, 7), (7, 9), (6, 8), (8, 10),
    (5, 11), (6, 12), (11, 12),
    (11, 13), (13, 15), (12, 14), (14, 16),
]

POSE_COLOR = (255, 200, 0)
POSE_LINE_COLOR = (255, 140, 0)
POSE_POINT_COLOR = (0, 165, 255)
WEAPON_COLOR = (0, 255, 0)
PERSON_TRACK_COLOR = (128, 0, 128)
STATUS_COLOR = (255, 255, 255)
ALERT_BANNER_COLOR = (0, 0, 255)
ALERT_TEXT_COLOR = (255, 255, 255)
