import cv2

try:
    from . import config_local as _local
except ImportError:
    _local = None


def _local_or_default(name, default):
    if _local is None:
        return default
    return getattr(_local, name, default)


WINDOW_NAME = "Security AI"
ALERT_WINDOW_NAME = "Security Alert"
MAIN_WINDOW_X = 80
MAIN_WINDOW_Y = 80
MAIN_WINDOW_WIDTH = 960
MAIN_WINDOW_HEIGHT = 720
ALERT_WINDOW_GAP = 24

CAMERA_INDEX = _local_or_default("CAMERA_INDEX", 2)
CAMERA_MIRROR = _local_or_default("CAMERA_MIRROR", False)
DEVICE = _local_or_default("DEVICE", "cuda:0")
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
CAMERA_BUFFER_SIZE = 1
PORTRAIT_ROTATION = None
ALERT_HOLD_SECONDS = 3.0
DELETE_OUTPUTS_ON_EXIT = True

CAMERA_BLOCK_CHANGE_RATIO_THRESHOLD = 0.35
CAMERA_BLOCK_MIN_BRIGHTNESS = 40.0
CAMERA_BLOCK_MIN_PIXEL_STD = 15.0
CAMERA_BLOCK_MIN_TEXTURE = 50.0
CAMERA_BLOCK_MIN_EDGE_RATIO = 0.02
CAMERA_BLOCK_HIST_THRESHOLD = 0.4
CAMERA_BLOCK_FLOW_THRESHOLD = 2.0
CAMERA_BLOCK_REQUIRED_CONSECUTIVE_FRAMES = 4
CAMERA_BLOCK_CAPTURE_INTERVAL_SECONDS = 1.0

WEAPON_MODEL_PATH = _local_or_default("WEAPON_MODEL_PATH", "models/yolo11l.pt")
POSE_MODEL_PATH = _local_or_default(
    "POSE_MODEL_PATH", "models/yolo11l-pose.pt")
PERSON_MODEL_PATH = _local_or_default("PERSON_MODEL_PATH", "models/yolo11l.pt")
PERSON_CONFIDENCE = 0.2
PERSON_IMAGE_SIZE = 960
LOITERING_THRESHOLD_SECONDS = 20.0
TRACKER_MAX_AGE = _local_or_default("TRACKER_MAX_AGE", 180)
TRACKER_N_INIT = _local_or_default("TRACKER_N_INIT", 5)
TRACKER_MAX_COSINE_DISTANCE = _local_or_default("TRACKER_MAX_COSINE_DISTANCE", 0.3)
REID_MATCH_THRESHOLD = _local_or_default("REID_MATCH_THRESHOLD", 0.78)
REID_TTL_SECONDS = _local_or_default("REID_TTL_SECONDS", 45)
REID_EMBEDDING_WEIGHT = _local_or_default("REID_EMBEDDING_WEIGHT", 0.55)
REID_HIST_WEIGHT = _local_or_default("REID_HIST_WEIGHT", 0.20)
REID_ORB_WEIGHT = _local_or_default("REID_ORB_WEIGHT", 0.15)
REID_SIZE_WEIGHT = _local_or_default("REID_SIZE_WEIGHT", 0.10)
REID_HIST_BLEND_ALPHA = _local_or_default("REID_HIST_BLEND_ALPHA", 0.20)
REID_ORB_DISTANCE_THRESHOLD = _local_or_default("REID_ORB_DISTANCE_THRESHOLD", 42)
REID_PROFILE_HISTORY = _local_or_default("REID_PROFILE_HISTORY", 6)
REID_MODEL_PATH = _local_or_default(
    "REID_MODEL_PATH", "models/person-reidentification-retail-0288.xml"
)
REID_INPUT_WIDTH = _local_or_default("REID_INPUT_WIDTH", 128)
REID_INPUT_HEIGHT = _local_or_default("REID_INPUT_HEIGHT", 256)
REID_MIN_EMBEDDING_SIMILARITY = _local_or_default("REID_MIN_EMBEDDING_SIMILARITY", 0.82)
REID_MIN_SIZE_SIMILARITY = _local_or_default("REID_MIN_SIZE_SIMILARITY", 0.55)

WEAPON_LABELS = _local_or_default("WEAPON_LABELS", {"knife", "baseball bat"})
PERSON_NEAR_AREA_THRESHOLD = 0.7
PERSON_NEAR_REQUIRED_TIME_SECONDS = 2.0
PERSON_NEAR_MIN_CONFIDENCE = 0.35
PERSON_NEAR_COOLDOWN_SECONDS = 3.0
PERSON_NEAR_HEAD_AREA_THRESHOLD = _local_or_default("PERSON_NEAR_HEAD_AREA_THRESHOLD", 0.30)
PERSON_NEAR_HEAD_KEYPOINT_CONFIDENCE = _local_or_default("PERSON_NEAR_HEAD_KEYPOINT_CONFIDENCE", 0.35)
PERSON_NEAR_MIN_VISIBLE_FACE_POINTS = _local_or_default("PERSON_NEAR_MIN_VISIBLE_FACE_POINTS", 3)
DOOR_LOCK_ROI_X_RATIO = 0.30
DOOR_LOCK_ROI_Y_RATIO = 0.65
DOOR_LOCK_ROI_WIDTH_RATIO = 0.28
DOOR_LOCK_ROI_HEIGHT_RATIO = 0.23
DOOR_LOCK_CONTACT_ROI_WIDTH_RATIO = 0.50
DOOR_LOCK_CONTACT_ROI_HEIGHT_RATIO = 0.25
DOOR_LOCK_WRIST_CONFIDENCE_THRESHOLD = 0.5
DOOR_LOCK_REQUIRED_SECONDS = 4.0
DOOR_LOCK_MISS_GRACE_SECONDS = 1.0
DOOR_LOCK_MOVEMENT_HISTORY_SIZE = 20
DOOR_LOCK_DECAY_FRAMES = 2
DOOR_LOCK_MOVEMENT_DELTA_THRESHOLD = 25
DOOR_LOCK_MIN_PERSON_HEIGHT_RATIO = 0.62
DOOR_LOCK_MIN_SHOULDER_WIDTH_RATIO = 0.26
DOOR_LOCK_HAND_EXTENSION_RATIO = 0.45
DOOR_LOCK_WRIST_DISTANCE_SHOULDER_RATIO = 0.22
DOOR_LOCK_MIN_WRIST_DISTANCE_PIXELS = 12
DOOR_LOCK_COOLDOWN_SECONDS = 3.0

POSE_CONNECTIONS = [
    (0, 1), (0, 2), (1, 3), (2, 4),
    (5, 6), (5, 7), (7, 9), (6, 8), (8, 10),
    (5, 11), (6, 12), (11, 12),
    (11, 13), (13, 15), (12, 14), (14, 16),
]

POSE_COLOR = (255, 200, 0)
POSE_LINE_COLOR = (255, 140, 0)
POSE_POINT_COLOR = (0, 165, 255)
WEAPON_COLOR = (0, 255, 0)
PERSON_TRACK_COLOR = (128, 0, 128)
STATUS_COLOR = (255, 255, 255)
ALERT_BANNER_COLOR = (0, 0, 255)
ALERT_TEXT_COLOR = (255, 255, 255)
